### ISSUE TITLE
darktheme fontcolor

### ISSUE THREAD

**Issue by ikuria** [itsmeow/HPOmenMindframeControl#1]
can you pls set the fontcolor for windows darktheme?
dark on dark is not readable for me :(
but i like your work, was always searching for this kind of tool just to remove the omen software, thanks!

**Comment by itsmeow** [comment]
What does it look like on your computer? I use Windows dark theme, but it appears fine for me. Can you post a screenshot?

**Comment by itsmeow** [comment]
![image](https://user-images.githubusercontent.com/10366817/93692392-b7a61080-fac0-11ea-88aa-5899a4d88f00.png)

**Comment by ikuria** [comment]
![omentool](https://user-images.githubusercontent.com/16177066/93692404-32881f00-faf3-11ea-99ab-e430104659b9.png)
hmm strange :/

**Comment by itsmeow** [comment]
What version of Windows are you on? Might be an Insider sorta thing

**Comment by ikuria** [comment]
found out, its a theme related problem, sorry for annoying you with that - but the most tools are working fine, dont know which font color you are using there

**Comment by itsmeow** [comment]
I think it's #e8e8e8
