### ISSUE TITLE
Cooling current control

### ISSUE THREAD

**Issue by RathX** [itsmeow/HPOmenMindframeControl#2]
Hey,
first of all great work, the software is really good.
I wanted to ask if you know wether the electrical current can be controlled inside the headset, since theoretically in thermoelectric coolers you could invert the current so that the headset would heat inside and cool outside, right? 
Would be neat to have this feature in the winter.

**Comment by itsmeow** [comment]
I have no idea. I believe you'd have to physically turn around the cooler inside your headset to do that, I don't think that's how electronics work. Either way I don't really want to subvert the SDK and send negative signals to the headset, sounds like a good way to break it. I might just though, considering my headset is getting replaced on warranty and I'll have an extra sitting around to experiment on...
