### ISSUE TITLE
Is the cooling configuration saved when exiting the software?

### ISSUE THREAD

**Issue by dfg555** [itsmeow/HPOmenMindframeControl#3]
If I have cooling to the max will it also save when used on another PC that doesn't have your program/HP Gaming Hub? Or does it use some default setting that HP has?

**Comment by itsmeow** [comment]
The cooling setting is saved to the Windows Registry of your current user account, and is applied next time the program is opened (not on system startup)

I believe the headset does save some of its settings in its onboard memory possibly but the program itself will override that when it is opened and trigger whatever it had last saved in the registry.
